### ISSUE TITLE
package compile order

### ISSUE THREAD

**Issue by phantomgz** [lachs0r/mingw-w64-cmake#22] opened 2015-12-17 04:00 UTC
When I build mpv with this script, It's have a very strange behavior, sometime can build sucess, sometime failed, after some digging, I found maybe some package building depending on other package, but at this time the other package still building or downloading, and so the error happenning. 
but sometime the being depended package building finnish first, it's can go through and build success.

Like for building libdvdread, it rely on libdvdcss, but often happen, libdvdread being building before libdvdcss finish it job. it's make libdvdread failed.

sorry for my pool english.

thanks.

**Comment by lachs0r** [comment] 2015-12-17 04:09
That shouldn’t happen. What’s your operating system and CMake version?

**Comment by phantomgz** [comment] 2015-12-17 08:09
ubuntu 14.01(64bit) + cmake version 2.8.12.2

**Comment by lachs0r** [comment] 2015-12-17 08:47
Try updating to CMake 3.3.

**Comment by phantomgz** [comment] 2015-12-17 15:11
update to cmake upgrade to 3.3.2,  but the problem still exist.
at this time at lease two package had failed at configure stage.

lame-configure-err.log:
```    
    /home/lachs0r.git/build-64/packages/lame-prefix/src/lame/configure: line 16126: syntax error near unexpected token `SNDFILE,'
    /home/lachs0r.git/build-64/packages/lame-prefix/src/lame/configure: line 16126: `  PKG_CHECK_MODULES(SNDFILE, sndfile >= 1.0.2, HAVE_SNDFILE="yes", HAVE_SNDFILE="no")'
```

libdvdread-configure-error.log:
```
    /home/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread/configure: line 12769: syntax error near unexpected token `CSS,'
    /home/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread/configure: line 12769: `  PKG_CHECK_MODULES(CSS, $CSS_REQUIRES)'
```

**Comment by phantomgz** [comment] 2015-12-17 15:17
this is only build only the libdvdread

```
~/lachs0r.git/build-64$ ninja libdvdread
[2/18] Performing force-update step for 'libdvdcss'
-- libdvdcss force-update command succeeded.  See also /home/phantom/lachs0r.git/build-64/packages/libdvdcss-prefix/src/libdvdcss-stamp/libdvdcss-force-update-*.log

[4/17] Performing force-update step for 'libdvdread'
-- libdvdread force-update command succeeded.  See also /home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread-stamp/libdvdread-force-update-*.log

[4/14] Performing autoreconf step for 'libdvdcss'
-- libdvdcss autoreconf command succeeded.  See also /home/phantom/lachs0r.git/build-64/packages/libdvdcss-prefix/src/libdvdcss-stamp/libdvdcss-autoreconf-*.log

[5/14] Performing configure step for 'libdvdcss'
-- libdvdcss configure command succeeded.  See also /home/phantom/lachs0r.git/build-64/packages/libdvdcss-prefix/src/libdvdcss-stamp/libdvdcss-configure-*.log

[6/14] Performing build step for 'libdvdcss'
-- libdvdcss build command succeeded.  See also /home/phantom/lachs0r.git/build-64/packages/libdvdcss-prefix/src/libdvdcss-stamp/libdvdcss-build-*.log

[8/14] Performing install step for 'libdvdcss'
-- libdvdcss install command succeeded.  See also /home/phantom/lachs0r.git/build-64/packages/libdvdcss-prefix/src/libdvdcss-stamp/libdvdcss-install-*.log

[10/14] Performing configure step for 'libdvdread'
FAILED: cd /home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread-build && /usr/bin/cmake -P /home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread-stamp/libdvdread-configure.cmake && /usr/bin/cmake -E touch /home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread-stamp/libdvdread-configure
CMake Error at /home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread-stamp/libdvdread-configure.cmake:16 (message):
  Command failed: 2

   '/home/phantom/lachs0r.git/build-64/exec' '/home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread/configure' '--host=x86_64-w64-mingw32' '--prefix=/home/phantom/lachs0r.git/build-64/prefix/mingw' '--disable-shared' '--with-libdvdcss'

  See also

    /home/phantom/lachs0r.git/build-64/packages/libdvdread-prefix/src/libdvdread-stamp/libdvdread-configure-*.log



ninja: build stopped: subcommand failed.

```

**Comment by lachs0r** [comment] 2015-12-17 15:23
Well, I cannot reproduce this at all. I’m just going to blame Ubuntu LTS 
because it’s the Windows XP of Linux distributions.
Most of its packages were outdated two years ago and it’s just not worth 
trying to support such old and broken crap with this toolchain.

Try using the VM image.

**Comment by phantomgz** [comment] 2015-12-17 16:07
very strange, sometime build would sucess, but after I make some code modify of mpv, and build again, 
this issue happen, but the building stage far away to mpv.

**Comment by lachs0r** [comment] 2015-12-17 16:19
That’s because by default, it updates and rebuilds packages that are pulled 
from version control sources (Git, SVN).

**Comment by phantomgz** [comment] 2015-12-17 16:33
I have try "-DENABLE_VCS_UPDATES=false" as you mention in README, building step would skip git download, but would still run patch command, and make some error, so I give up use "-DENABLE_VCS_UPDATES=false" option.

**Comment by lachs0r** [comment] 2015-12-17 16:41
Did you try this on a clean build directory?

**Comment by phantomgz** [comment] 2015-12-17 16:48
ok, I'll try again later

**Comment by chainikdn** [comment] 2017-02-13 12:24
'libvpx' should depend on 'gcc', not 'winpthreads'

**Comment by lachs0r** [comment] 2017-02-13 12:57
That’s fixed now.

**Closed** 2017-02-14 09:44 UTC
